In [12]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression

iris = datasets.load_iris()
# 选择数据集的特征，第4列（花瓣宽度）作为输入特征
x = iris['data'][:,3:]
# 创建二分类目标变量，将目标变量等于2的样本标记为1，其余为0
# .astype(np.int_)：将布尔数组转换为整数数组，其中True转换为1，False转换为0
y = (iris['target'] == 2).astype(np.int_)
x,y

(array([[0.2],
        [0.2],
        [0.2],
        [0.2],
        [0.2],
        [0.4],
        [0.3],
        [0.2],
        [0.2],
        [0.1],
        [0.2],
        [0.2],
        [0.1],
        [0.1],
        [0.2],
        [0.4],
        [0.4],
        [0.3],
        [0.3],
        [0.3],
        [0.2],
        [0.4],
        [0.2],
        [0.5],
        [0.2],
        [0.2],
        [0.4],
        [0.2],
        [0.2],
        [0.2],
        [0.2],
        [0.4],
        [0.1],
        [0.2],
        [0.2],
        [0.2],
        [0.2],
        [0.1],
        [0.2],
        [0.2],
        [0.3],
        [0.3],
        [0.2],
        [0.6],
        [0.4],
        [0.3],
        [0.2],
        [0.2],
        [0.2],
        [0.2],
        [1.4],
        [1.5],
        [1.5],
        [1.3],
        [1.5],
        [1.3],
        [1.6],
        [1. ],
        [1.3],
        [1.4],
        [1. ],
        [1.5],
        [1. ],
        [1.4],
        [1.3],
        [1.4],
        [1

In [13]:
# 创建逻辑回归模型，使用sag随机梯度下降，并设置最大迭代次数为1000
binary_classifier = LogisticRegression(solver='sag',max_iter=1000)
# 用特征x和目标变量y训练逻辑回归模型
binary_classifier.fit(x,y)

# 生成从0到3之间的1000个等间距的点，并将其形状调整为列向量
x_new = np.linspace(0,3,1000).reshape(-1,1)
y_proba = binary_classifier.predict_proba(x_new)  # 计算新数据点的类别概率
y_hat = binary_classifier.predict(x_new) # 预测新数据点的类别
y_proba,y_hat

(array([[9.99249976e-01, 7.50024248e-04],
        [9.99240160e-01, 7.59839962e-04],
        [9.99230216e-01, 7.69784036e-04],
        ...,
        [3.08403048e-03, 9.96915970e-01],
        [3.04428204e-03, 9.96955718e-01],
        [3.00504435e-03, 9.96994956e-01]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

### 拓展 逻辑回归进行多分类

In [14]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression

iris = datasets.load_iris()
# 选择数据集的特征，第4列（花瓣宽度）作为输入特征
x = iris['data'][:,3:]
# 会有0，1，2三个类别
y = iris['target']

In [15]:
# 创建逻辑回归模型，使用sag随机梯度下降，并设置最大迭代次数为1000 ,one-over-rest
multi_classifier = LogisticRegression(solver='sag',max_iter=1000,multi_class='ovr')
# 用特征x和目标变量y训练逻辑回归模型
multi_classifier.fit(x,y)

# 生成从0到3之间的1000个等间距的点，并将其形状调整为列向量
x_new = np.linspace(0,3,1000).reshape(-1,1)
y_proba = multi_classifier.predict_proba(x_new)  # 计算新数据点的类别概率
y_hat = multi_classifier.predict(x_new) # 预测新数据点的类别
y_proba,y_hat

(array([[7.92351133e-01, 2.07035260e-01, 6.13607179e-04],
        [7.92156744e-01, 2.07221501e-01, 6.21754686e-04],
        [7.91961227e-01, 2.07408760e-01, 6.30012986e-04],
        ...,
        [2.67300615e-05, 3.18779298e-01, 6.81193972e-01],
        [2.63637795e-05, 3.18880949e-01, 6.81092687e-01],
        [2.60025261e-05, 3.18982679e-01, 6.80991318e-01]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0